### ISSUE TITLE
binary file detection

### ISSUE THREAD

**Issue by cheyilin** [rybbchao/fops#1]
Please check the [`http.DetectContentType`](https://golang.org/pkg/net/http/#DetectContentType) and find a way to detect non-text files.

And please remember to add related tests and revise the README, thank you.

**Comment by rybbchao** [comment]
I tried to use [http.DetectContentType](https://golang.org/pkg/net/http/#DetectContentType) to detect the files.

`fops`, a binary file built from this repository and `README.md` works well.
However, some text file will get the wrong type `application/octet-stream`.
For example,
```
cat <<EOF > myfile.txt
how do
you
turn this
on
EOF
```

My Environment is as below:

```
MacOS: 10.15.1
Go: 1.13.5
```

Here's the screenshot of the outputs, Thank you.
![Screen Shot 2019-12-19 at 3 38 42 AM](https://user-images.githubusercontent.com/17705238/71117916-06f9a080-2212-11ea-986b-474ede98d4c1.png)

**Comment by cheyilin** [comment]
You're right, [`http.DetectContentType`](https://golang.org/pkg/net/http/#DetectContentType) only implemented HTML like types detection [see](https://golang.org/src/net/http/sniff.go), unsupported types will be `application/octet-stream`.

Try using 3rd-party module like [`gabriel-vasile/mimetype`](https://github.com/gabriel-vasile/mimetype).

**Comment by cheyilin** [comment]
Verified, thanks for the fix. Close now.
